### ISSUE TITLE
Pull request merging issue

### ISSUE THREAD

**Issue by arlincherian** [UBC-MDS/CoordGeomPy#2]
I've added a function on the src folder doc and sent a pull request but looks like there are some merging issues. Can someone check as well to see what this might be?

**Comment by jcasoli** [comment]
I found this issue that may help: https://stackoverflow.com/questions/69659712/poetry-run-worker-py-filenotfound-errno-2-no-such-file-or-directory-b-snap

One suggestion was that maybe there is some error in our pyproject.toml file. But I took a look and nothing stood out to me..

**Comment by jcasoli** [comment]
Ohhh it also could be something to do with the pytest module. Maybe it doesn't exist wherever these tests are being run?

**Comment by arlincherian** [comment]
I also noticed that the initial package setup commit also has an 'x' next to it in the commit history..not sure if that is related but worth checking.

**Comment by jcasoli** [comment]
Looks like it's the same issue. I'll post a message in the course slack channel to see if anyone has any ideas.

**Comment by jcasoli** [comment]
Should we just merge your PR while we sort this out? I took a look in some other group repo's and they are having the same error message

**Comment by arlincherian** [comment]
if we have some time at the end of the class today, I can ask tiffany about it before we go ahead with the merge. I'll keep you posted.
