### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/CoordGeomPy#53]
Here was the general structure that we just discussed, feel free to edit this/add to it as needed:

- Introduction
- Problem scope
- Similar packages that exist
- Description of our package
- Potential live demo or explanation of functions
- Conclusion

**Comment by arlincherian** [comment]
Thanks, Nico. I have shared a google link in the slack channel and transferred these topics there as well.

**Comment by nicovandenhooff** [comment]
Closing since we have the google slides now.
