### ISSUE TITLE
Review of Licenses for Python and R packages

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/CoordGeomPy#56]
As per DSCI 524 milestone 4, we need to:

> *Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories. As it is likely to be a very similar discussion for both projects, one of these issues can just link to the other issue where it is thoroughly discussed.*

The purpose of this issue is to contain the discussion for the above analysis, for both our Python (coordgeompy) and R (CoordGeomR) packages.

As of the creation of this issue, both the licenses in our Python and R packages are the MIT License.

Resources for discussion:
- https://choosealicense.com/
- https://chooser-beta.creativecommons.org/
- https://pages.github.ubc.ca/mds-2021-22/DSCI_524_collab-sw-dev_students/materials/lectures/08_lecture-who-owns-the-code-and-how-can-I-use-it.html

**Comment by arlincherian** [comment]
Thanks for opening up the discussion, Nico. I think both `coordgeompy` and `CoordGeomR` packages can evolve with input from Python and R communities. Our current choice of MIT license for these packages will allow users to use the license for commercial use, distribution and modification with some limitations on liability and warranty as stated in our license document. This license is also well known among the data science community so users interested in modifying or using this package will have some familiarity with it. 
What are your thoughts?

**Comment by nicovandenhooff** [comment]
In short I agree with @arlincherian - I think we should just stick with the MIT license.  

Notes I took during tiffs lecture:
- https://choosealicense.com/ which can help us determine which license to use
- Based on the above website I think we can stick with the MIT license since our project is a simple piece of software
- GNU license is a bit too complex for our project I think
- I don't think we need a Creative Commons license since this project is only code

**Comment by nicovandenhooff** [comment]
As discussed on the slack call on February 4, 2022 we will be keeping the MIT license for both our Python and R packages.
